on:
  workflow_call:
    inputs:
      test-input:
        required: false
        type: string
        default: "this is an input"
      fail:
        required: true
        type: string
        default: no

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello World")
        name: Run Python Script
        shell: python

      - uses: actions/github-script@v6
        name: "Run GitHub Script"
        with:
          script: |
            console.log("Hello World")
            return "Hello World"
          result-encoding: string

      - name: Fail the job
        if: ${{ inputs.fail == 'second' }}
        run: exit 1